services:
    rk_download_module.link_container:
        class: RK\DownLoadModule\Container\LinkContainer
        arguments:
            - "@translator.default"
            - "@router"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_users_module.current_user"
            - "@rk_download_module.controller_helper"
        tags:
            - { name: zikula.link_container }
